/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

/**
 *
 * @author cindybohorquezsantana
 */
public class Interfaz_MenuCliente extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_RegistrarCompra
     */
    public Interfaz_MenuCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegistrarCliente = new javax.swing.JButton();
        jButtonBuscarCliente = new javax.swing.JButton();
        jButtonAtrasAEmpleado = new javax.swing.JButton();
        jLabelImgRegistrarCliente = new javax.swing.JLabel();
        jLabelBuscarCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jLabelFondoInterfazCompra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegistrarCliente.setText("Registrar Cliente");
        jButtonRegistrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegistrarClienteMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jButtonBuscarCliente.setText("Buscar Cliente");
        jButtonBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarClienteMouseClicked(evt);
            }
        });
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 150, -1));

        jButtonAtrasAEmpleado.setText("ATRÁS");
        jButtonAtrasAEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasAEmpleadoMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAtrasAEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabelImgRegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cliente.png"))); // NOI18N
        getContentPane().add(jLabelImgRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 50, 50));

        jLabelBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        getContentPane().add(jLabelBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yuppy SC", 0, 30)); // NOI18N
        jLabel1.setText("Menú del Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabelFondoInterfazCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall.png"))); // NOI18N
        jLabelFondoInterfazCompra.setText("jLabel1");
        getContentPane().add(jLabelFondoInterfazCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasAEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasAEmpleadoMouseClicked
        // TODO add your handling code here:
        Interfaz_Empleado iE = new Interfaz_Empleado();
            iE.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButtonAtrasAEmpleadoMouseClicked

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jButtonRegistrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarClienteMouseClicked
        // TODO add your handling code here:
        Interfaz_Registro iReg = new Interfaz_Registro();
            iReg.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButtonRegistrarClienteMouseClicked

    private void jButtonBuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteMouseClicked
        // TODO add your handling code here:
        Interfaz_BuscarCliente iBC = new Interfaz_BuscarCliente();
            iBC.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButtonBuscarClienteMouseClicked

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_MenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtrasAEmpleado;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonRegistrarCliente;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBuscarCliente;
    private javax.swing.JLabel jLabelFondoInterfazCompra;
    private javax.swing.JLabel jLabelImgRegistrarCliente;
    // End of variables declaration//GEN-END:variables
}
