/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

/**
 *
 * @author cindybohorquezsantana
 */
public class Interfaz_Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Administrador
     */
    public Interfaz_Administrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jCheckBoxVerListaDeProveedores = new javax.swing.JCheckBox();
        jCheckBoxVerListaDeEmpleados = new javax.swing.JCheckBox();
        jCheckBoxVerListaDeclientes = new javax.swing.JCheckBox();
        jCheckBoxRegistrarPreciosDeCortinas = new javax.swing.JCheckBox();
        jCheckBoxRegistarPreciosDeAlquilerDeCortinas = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabelAtrás = new javax.swing.JLabel();
        jLabelNEXT = new javax.swing.JLabel();
        jLabelFondoAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBoxVerListaDeProveedores.setText("Ver Lista De Proveedores");
        getContentPane().add(jCheckBoxVerListaDeProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jCheckBoxVerListaDeEmpleados.setText("Ver Lista De Empleados");
        getContentPane().add(jCheckBoxVerListaDeEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jCheckBoxVerListaDeclientes.setText("Ver Lista De Clientes");
        getContentPane().add(jCheckBoxVerListaDeclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jCheckBoxRegistrarPreciosDeCortinas.setText("Registrar Precios De Cortinas");
        getContentPane().add(jCheckBoxRegistrarPreciosDeCortinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jCheckBoxRegistarPreciosDeAlquilerDeCortinas.setText("Registar Precios De Alquiler De Cortinas");
        getContentPane().add(jCheckBoxRegistarPreciosDeAlquilerDeCortinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yuppy SC", 0, 30)); // NOI18N
        jLabel1.setText("Menú del Administrador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabelAtrás.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atrás.png"))); // NOI18N
        jLabelAtrás.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAtrásMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAtrás, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabelNEXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/next.png"))); // NOI18N
        getContentPane().add(jLabelNEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        jLabelFondoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall.png"))); // NOI18N
        getContentPane().add(jLabelFondoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 320));

        pack();
    }// </editor-fold>                        

    private void jLabelAtrásMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        InterfazPrincipal iP = new InterfazPrincipal();
            iP.setVisible(true);
            this.dispose();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox jCheckBoxRegistarPreciosDeAlquilerDeCortinas;
    private javax.swing.JCheckBox jCheckBoxRegistrarPreciosDeCortinas;
    private javax.swing.JCheckBox jCheckBoxVerListaDeEmpleados;
    private javax.swing.JCheckBox jCheckBoxVerListaDeProveedores;
    private javax.swing.JCheckBox jCheckBoxVerListaDeclientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAtrás;
    private javax.swing.JLabel jLabelFondoAdmin;
    private javax.swing.JLabel jLabelNEXT;
    // End of variables declaration                   
}
