/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;


/**
 *
 * @author cindybohorquezsantana
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public InterfazPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSALIR = new javax.swing.JButton();
        jButtonSIGUIENTE = new javax.swing.JButton();
        jComboBoxROLL = new javax.swing.JComboBox<>();
        jLabelLOGO = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSALIR.setText("SALIR");
        jButtonSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jButtonSIGUIENTE.setText("SIGUIENTE");
        jButtonSIGUIENTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSIGUIENTEMouseClicked(evt);
            }
        });
        jButtonSIGUIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSIGUIENTEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSIGUIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jComboBoxROLL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado" }));
        jComboBoxROLL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxROLLActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxROLL, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 270, 30));

        jLabelLOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        getContentPane().add(jLabelLOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("PilGi", 0, 55)); // NOI18N
        jLabel1.setText("Vive Hogar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelFONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall.png"))); // NOI18N
        getContentPane().add(jLabelFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 280));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSIGUIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSIGUIENTEActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonSIGUIENTEActionPerformed

    private void jButtonSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSALIRActionPerformed
             // TODO add your handling code here:
             System.exit(0);
    }//GEN-LAST:event_jButtonSALIRActionPerformed

    private void jButtonSIGUIENTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSIGUIENTEMouseClicked
        // TODO add your handling code here:
        int cb = jComboBoxROLL.getSelectedIndex();
        if(cb==0){
            //abrir ventana administrador
            Interfaz_Administrador iA = new Interfaz_Administrador();
            iA.setVisible(true);
            this.dispose();
        }
        else{
            //abrir ventana empleado
            Interfaz_Empleado iE = new Interfaz_Empleado();
            iE.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_jButtonSIGUIENTEMouseClicked

    private void jComboBoxROLLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxROLLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxROLLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSALIR;
    private javax.swing.JButton jButtonSIGUIENTE;
    private javax.swing.JComboBox<String> jComboBoxROLL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFONDO;
    private javax.swing.JLabel jLabelLOGO;
    // End of variables declaration//GEN-END:variables
}
