/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;


/**
 *
 * @author cindybohorquezsantana
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public InterfazPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jComboBoxROLL = new javax.swing.JComboBox<>();
        jLabelLOGO = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2NEXT = new javax.swing.JLabel();
        jLabel2SALIR = new javax.swing.JLabel();
        jLabelFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxROLL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado" }));
        jComboBoxROLL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxROLLActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxROLL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 250, 30));

        jLabelLOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        getContentPane().add(jLabelLOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -10, -1, -1));

        jLabel1.setFont(new java.awt.Font("PilGi", 0, 55)); // NOI18N
        jLabel1.setText("Vive Hogar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 260, 60));

        jLabel2NEXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/next.png"))); // NOI18N
        jLabel2NEXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2NEXTMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2NEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        jLabel2SALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jLabel2SALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2SALIRMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabelFONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall.png"))); // NOI18N
        getContentPane().add(jLabelFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 220));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>                        

    private void jComboBoxROLLActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jLabel2NEXTMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
                int cb = jComboBoxROLL.getSelectedIndex();
        if(cb==0){
            //abrir ventana administrador
            Interfaz_Administrador iA = new Interfaz_Administrador();
            iA.setVisible(true);
            this.dispose();
        }
        else{
            //abrir ventana empleado
            Interfaz_Empleado iE = new Interfaz_Empleado();
            iE.setVisible(true);
            this.dispose();
        }
    }                                        

    private void jLabel2SALIRMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        System.exit(0);
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> jComboBoxROLL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2NEXT;
    private javax.swing.JLabel jLabel2SALIR;
    private javax.swing.JLabel jLabelFONDO;
    private javax.swing.JLabel jLabelLOGO;
    // End of variables declaration                   
}
