/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

/**
 *
 * @author cindybohorquezsantana
 */
public class Interfaz_BuscarCliente extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_BuscarCliente
     */
    public Interfaz_BuscarCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCedula = new javax.swing.JLabel();
        jTextCedula = new javax.swing.JTextField();
        jButtonBUSCAR = new javax.swing.JButton();
        jLabelImagenLupa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButtonSIGUIENTEaFacturacion = new javax.swing.JButton();
        jLabelIMGFACTURA = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonATRASaMENUREGISTROCOMPRA = new javax.swing.JButton();
        jLabelFondoBuscarCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCedula.setText("Ingrese el número de Cédula:");
        getContentPane().add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        getContentPane().add(jTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 160, 30));

        jButtonBUSCAR.setText("BUSCAR");
        getContentPane().add(jButtonBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 110, 30));

        jLabelImagenLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        getContentPane().add(jLabelImagenLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 210, 190));

        jLabel1.setText("Datos Encontrados:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jButtonSIGUIENTEaFacturacion.setText("FACTURAR");
        jButtonSIGUIENTEaFacturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSIGUIENTEaFacturacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSIGUIENTEaFacturacionMouseEntered(evt);
            }
        });
        getContentPane().add(jButtonSIGUIENTEaFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabelIMGFACTURA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.png"))); // NOI18N
        getContentPane().add(jLabelIMGFACTURA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 110, 30));

        jLabel2.setFont(new java.awt.Font("Yuppy SC", 0, 24)); // NOI18N
        jLabel2.setText("Búsqueda");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jButtonATRASaMENUREGISTROCOMPRA.setText("ATRAS");
        jButtonATRASaMENUREGISTROCOMPRA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonATRASaMENUREGISTROCOMPRAMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonATRASaMENUREGISTROCOMPRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 110, 30));

        jLabelFondoBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall.png"))); // NOI18N
        getContentPane().add(jLabelFondoBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonATRASaMENUREGISTROCOMPRAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonATRASaMENUREGISTROCOMPRAMouseClicked
        // TODO add your handling code here:
        Interfaz_MenuCliente iMR = new Interfaz_MenuCliente();
            iMR.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButtonATRASaMENUREGISTROCOMPRAMouseClicked

    private void jButtonSIGUIENTEaFacturacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSIGUIENTEaFacturacionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSIGUIENTEaFacturacionMouseEntered

    private void jButtonSIGUIENTEaFacturacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSIGUIENTEaFacturacionMouseClicked
        // TODO add your handling code here:
        Interfaz_Facturación iF = new Interfaz_Facturación();
            iF.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButtonSIGUIENTEaFacturacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_BuscarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonATRASaMENUREGISTROCOMPRA;
    private javax.swing.JButton jButtonBUSCAR;
    private javax.swing.JButton jButtonSIGUIENTEaFacturacion;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelFondoBuscarCliente;
    private javax.swing.JLabel jLabelIMGFACTURA;
    private javax.swing.JLabel jLabelImagenLupa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextCedula;
    // End of variables declaration//GEN-END:variables
}
