/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

/**
 *
 * @author cindybohorquezsantana
 */
public class Interfaz_Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Administrador
     */
    public Interfaz_Administrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAtrasAInterfPrincipal = new javax.swing.JButton();
        jButtonSalirAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonProveedor = new javax.swing.JButton();
        jButtonEmpleado = new javax.swing.JButton();
        jButtonCliente = new javax.swing.JButton();
        jButtonPrecioCortina = new javax.swing.JButton();
        jButtonAlquilerCortina = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMostrarAdmin = new javax.swing.JTable();
        jLabelFondoAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAtrasAInterfPrincipal.setText("ATRÁS");
        jButtonAtrasAInterfPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasAInterfPrincipalMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAtrasAInterfPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jButtonSalirAdmin.setText("SALIR");
        jButtonSalirAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirAdminActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalirAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yuppy SC", 0, 30)); // NOI18N
        jLabel1.setText("Menú del Administrador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        jButtonProveedor.setText("Ver Lista De Proveedores");
        getContentPane().add(jButtonProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jButtonEmpleado.setText(" Ver Lista De Empleados  ");
        getContentPane().add(jButtonEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jButtonCliente.setText("     Ver Lista De Clientes   ");
        getContentPane().add(jButtonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jButtonPrecioCortina.setText("Registrar Precios De Cortinas");
        getContentPane().add(jButtonPrecioCortina, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jButtonAlquilerCortina.setText("Registar Precios De Alquiler De Cortinas");
        getContentPane().add(jButtonAlquilerCortina, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        getContentPane().add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, -1, -1));

        jTableMostrarAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTableMostrarAdmin);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 50, 420, 240));

        jLabelFondoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall.png"))); // NOI18N
        getContentPane().add(jLabelFondoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasAInterfPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasAInterfPrincipalMouseClicked
        // TODO add your handling code here:
        InterfazPrincipal iP = new InterfazPrincipal();
            iP.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButtonAtrasAInterfPrincipalMouseClicked

    private void jButtonSalirAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirAdminActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlquilerCortina;
    private javax.swing.JButton jButtonAtrasAInterfPrincipal;
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonEmpleado;
    private javax.swing.JButton jButtonPrecioCortina;
    private javax.swing.JButton jButtonProveedor;
    private javax.swing.JButton jButtonSalirAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondoAdmin;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMostrarAdmin;
    // End of variables declaration//GEN-END:variables
}
