/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

/**
 *
 * @author cindybohorquezsantana
 */
public class Interfaz_MenuCliente extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_RegistrarCompra
     */
    public Interfaz_MenuCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButtonRegistrarCliente = new javax.swing.JButton();
        jButtonBuscarCliente = new javax.swing.JButton();
        jLabelImgRegistrarCliente = new javax.swing.JLabel();
        jLabelBuscarCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonModificar = new javax.swing.JButton();
        jLabel2ImgEditra = new javax.swing.JLabel();
        jLabel2Atrás = new javax.swing.JLabel();
        jLabelELIMINAR = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelFondoInterfazCompra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegistrarCliente.setText("Registrar Cliente");
        jButtonRegistrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegistrarClienteMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, -1));

        jButtonBuscarCliente.setText("Buscar Cliente");
        jButtonBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarClienteMouseClicked(evt);
            }
        });
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 150, -1));

        jLabelImgRegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RegClient.png"))); // NOI18N
        getContentPane().add(jLabelImgRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 70, 70));

        jLabelBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        getContentPane().add(jLabelBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yuppy SC", 0, 30)); // NOI18N
        jLabel1.setText("Menú del Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButtonModificar.setText("Modificar Cliente");
        jButtonModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonModificarMouseClicked(evt);
            }
        });
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 150, 30));

        jLabel2ImgEditra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Editar.png"))); // NOI18N
        getContentPane().add(jLabel2ImgEditra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel2Atrás.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atrás.png"))); // NOI18N
        jLabel2Atrás.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2AtrásMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2Atrás, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        jLabelELIMINAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        getContentPane().add(jLabelELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jButton1.setText("Eliminar Cliente");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLabelFondoInterfazCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall.png"))); // NOI18N
        jLabelFondoInterfazCompra.setText("jLabel1");
        getContentPane().add(jLabelFondoInterfazCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 500));

        pack();
    }// </editor-fold>                        

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void jButtonRegistrarClienteMouseClicked(java.awt.event.MouseEvent evt) {                                                     
        // TODO add your handling code here:
        Interfaz_Registro iReg = new Interfaz_Registro();
            iReg.setVisible(true);
            this.dispose();
    }                                                    

    private void jButtonBuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {                                                  
        // TODO add your handling code here:
        Interfaz_BuscarCliente iBC = new Interfaz_BuscarCliente();
            iBC.setVisible(true);
            this.dispose();
    }                                                 

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void jButtonModificarMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
         Interfaz_Modificar iM = new Interfaz_Modificar();
            iM.setVisible(true);
            this.dispose();
    }                                             

    private void jLabel2AtrásMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
            Interfaz_Empleado iE = new Interfaz_Empleado();
            iE.setVisible(true);
            this.dispose();
    }                                         

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
           Interfaz_EliminarCliente EC  = new Interfaz_EliminarCliente();
            EC.setVisible(true);
            this.dispose();
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_MenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonRegistrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2Atrás;
    private javax.swing.JLabel jLabel2ImgEditra;
    private javax.swing.JLabel jLabelBuscarCliente;
    private javax.swing.JLabel jLabelELIMINAR;
    private javax.swing.JLabel jLabelFondoInterfazCompra;
    private javax.swing.JLabel jLabelImgRegistrarCliente;
    // End of variables declaration                   
}
