/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cindybohorquezsantana
 */
public class Interfaz_BuscarCliente extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_BuscarCliente
     */
    public Interfaz_BuscarCliente() {
        initComponents();
        mostrardatos("");
        this.setLocationRelativeTo(null);
    }
    void mostrardatos(String valor){
        Conectar cc=new Conectar();
        Connection cn=cc.getConnection();
        DefaultTableModel modelo=new DefaultTableModel();
       
        modelo.addColumn("CedCliente");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("dirección");
        modelo.addColumn("Teléfono");
        
        jTable1.setModel(modelo);
        String sql="";
        if (valor.equals(""))
        {
            sql="SELECT * FROM SIGEVAC.CLIENTES";
        }
        else{
            sql="SELECT * FROM SIGEVAC.CLIENTES WHERE (cedCliente='"+valor+"' )";
            //sql="SELECT * FROM iSIGEVAC.CLIENTES WHERE (cedCliente='"+valor+"'  OR nombre='"+valor+"')";
        }  
        
        String []datos=new String [5];
        try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            datos[4]=rs.getString(5);
            modelo.addRow(datos);
            }
            jTable1.setModel(modelo);
        }catch(SQLException ex){
            Logger.getLogger(datos.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelCedula = new javax.swing.JLabel();
        jTextCedula = new javax.swing.JTextField();
        jLabelImagenLupa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelIMGFACTURA = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3_Mostrar = new javax.swing.JLabel();
        jLabelAtrás = new javax.swing.JLabel();
        jLabelSALIR = new javax.swing.JLabel();
        jLabelFondoBuscarCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCedula.setText("Ingrese el número de Cédula:");
        getContentPane().add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 190, -1));
        getContentPane().add(jTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 150, 30));

        jLabelImagenLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jLabelImagenLupa.setText("BUSCAR");
        jLabelImagenLupa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImagenLupaMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelImagenLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 133, -1));

        jLabel1.setText("Datos Encontrados:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jLabelIMGFACTURA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.png"))); // NOI18N
        jLabelIMGFACTURA.setText("FACTURAR");
        getContentPane().add(jLabelIMGFACTURA, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 135, 60));

        jLabel2.setFont(new java.awt.Font("Yuppy SC", 0, 36)); // NOI18N
        jLabel2.setText("Búsqueda");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 470, 340));

        jLabel3_Mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mostrar.png"))); // NOI18N
        jLabel3_Mostrar.setText("MOSTRAR");
        jLabel3_Mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3_MostrarMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3_Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 133, -1));

        jLabelAtrás.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atrás.png"))); // NOI18N
        jLabelAtrás.setText("ATRÁS");
        jLabelAtrás.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAtrásMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAtrás, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 135, -1));

        jLabelSALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jLabelSALIR.setText("SALIR");
        jLabelSALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSALIRMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 135, -1));

        jLabelFondoBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall.png"))); // NOI18N
        getContentPane().add(jLabelFondoBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 470));

        pack();
    }// </editor-fold>                        

    private void jLabelImagenLupaMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
        mostrardatos(jTextCedula.getText());
    }                                             

    private void jLabel3_MostrarMouseClicked(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
        mostrardatos("");
    }                                            

    private void jLabelAtrásMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
            Interfaz_MenuCliente iMR = new Interfaz_MenuCliente();
            iMR.setVisible(true);
            this.dispose();
    }                                        

    private void jLabelSALIRMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_BuscarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3_Mostrar;
    private javax.swing.JLabel jLabelAtrás;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelFondoBuscarCliente;
    private javax.swing.JLabel jLabelIMGFACTURA;
    private javax.swing.JLabel jLabelImagenLupa;
    private javax.swing.JLabel jLabelSALIR;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextCedula;
    // End of variables declaration                   
}
