/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author cindybohorquezsantana
 */
public class Interfaz_Registro extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Registro
     */
    public Interfaz_Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNOMBRE = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelTelfConvencional = new javax.swing.JLabel();
        jLabelCédula = new javax.swing.JLabel();
        jLabelDirección = new javax.swing.JLabel();
        jTextNOMBRE = new javax.swing.JTextField();
        jTextAPellido = new javax.swing.JTextField();
        jTextCedula = new javax.swing.JTextField();
        jTextDireccion = new javax.swing.JTextField();
        jTextTelfConv = new javax.swing.JTextField();
        jButtonREGISTRAR = new javax.swing.JButton();
        jButtonSIGUIENTEaFacturacion = new javax.swing.JButton();
        jButtonATRÁS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFondoRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNOMBRE.setText("Nombre:");
        getContentPane().add(jLabelNOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabelApellido.setText("Apellido:");
        getContentPane().add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabelTelfConvencional.setText("Telf Conv.:");
        getContentPane().add(jLabelTelfConvencional, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabelCédula.setText("#Cédula:");
        getContentPane().add(jLabelCédula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabelDirección.setText("Dirección:");
        getContentPane().add(jLabelDirección, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jTextNOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNOMBREActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 300, 30));

        jTextAPellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAPellidoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextAPellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 300, 30));

        jTextCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 300, 30));
        getContentPane().add(jTextDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 300, 30));
        getContentPane().add(jTextTelfConv, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 300, 30));

        jButtonREGISTRAR.setText("REGISTRAR");
        jButtonREGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREGISTRARActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        jButtonSIGUIENTEaFacturacion.setText("FACTURAR");
        jButtonSIGUIENTEaFacturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSIGUIENTEaFacturacionMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonSIGUIENTEaFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        jButtonATRÁS.setText("ATRÁS");
        jButtonATRÁS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonATRÁSMouseClicked(evt);
            }
        });
        jButtonATRÁS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonATRÁSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonATRÁS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yuppy SC", 0, 30)); // NOI18N
        jLabel1.setText("Menú de Registro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabelFondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall.png"))); // NOI18N
        getContentPane().add(jLabelFondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNOMBREActionPerformed

    private void jTextAPellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAPellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAPellidoActionPerformed

    private void jTextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCedulaActionPerformed

    private void jButtonREGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREGISTRARActionPerformed
        // TODO add your handling code here:
        Conectar conecta=new Conectar();
        Connection reg = conecta.getConnection();
        try{
            PreparedStatement pst=reg.prepareStatement("INSERT INTO clientes(cedCliente,nombreCliente,apellidoCliente,direccionCliente,telefonoCliente) VALUES(?,?,?,?,?)");
            pst.setString(1,jTextCedula.getText());
            pst.setString(2,jTextNOMBRE.getText());
            pst.setString(3,jTextAPellido.getText());
            pst.setString(4,jTextDireccion.getText());
            pst.setString(5,jTextTelfConv.getText());
            
            
        int a=pst.executeUpdate();
        if(a>0){
            JOptionPane.showMessageDialog(null,"Registro exitoso");
        }
        else{
             JOptionPane.showMessageDialog(null,"Error al agregar");
        }
        }catch(Exception e){
        } 
    }//GEN-LAST:event_jButtonREGISTRARActionPerformed

    private void jButtonATRÁSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonATRÁSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonATRÁSActionPerformed

    private void jButtonATRÁSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonATRÁSMouseClicked
        // TODO add your handling code here:
        Interfaz_MenuCliente iRC = new Interfaz_MenuCliente();
            iRC.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButtonATRÁSMouseClicked

    private void jButtonSIGUIENTEaFacturacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSIGUIENTEaFacturacionMouseClicked
        // TODO add your handling code here:
        Interfaz_Facturación iF = new Interfaz_Facturación();
            iF.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButtonSIGUIENTEaFacturacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Interfaz_Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonATRÁS;
    private javax.swing.JButton jButtonREGISTRAR;
    private javax.swing.JButton jButtonSIGUIENTEaFacturacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCédula;
    private javax.swing.JLabel jLabelDirección;
    private javax.swing.JLabel jLabelFondoRegistro;
    private javax.swing.JLabel jLabelNOMBRE;
    private javax.swing.JLabel jLabelTelfConvencional;
    private javax.swing.JTextField jTextAPellido;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextNOMBRE;
    private javax.swing.JTextField jTextTelfConv;
    // End of variables declaration//GEN-END:variables
}
