/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

/**
 *
 * @author cindybohorquezsantana
 */
public class Interfaz_Facturación extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Facturación
     */
    public Interfaz_Facturación() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonTotalAPagar = new javax.swing.JButton();
        jTextTotalAPagar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonSALIR = new javax.swing.JButton();
        jButton1IrAmenúcliente = new javax.swing.JButton();
        jLabelFondoFacturacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 450, 120));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CodProducto", "Cantidad", "Descripción", "Precio"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jButtonTotalAPagar.setText("Total a Pagar");
        getContentPane().add(jButtonTotalAPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));
        getContentPane().add(jTextTotalAPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, 170, -1));

        jLabel1.setFont(new java.awt.Font("Yuppy TC", 0, 40)); // NOI18N
        jLabel1.setText("Factura");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        jButtonSALIR.setText("SALIR");
        jButtonSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, -1, -1));

        jButton1IrAmenúcliente.setText("Ir a Menú de Cliente");
        jButton1IrAmenúcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1IrAmenúclienteMouseClicked(evt);
            }
        });
        getContentPane().add(jButton1IrAmenúcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 670, -1, -1));

        jLabelFondoFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall.png"))); // NOI18N
        getContentPane().add(jLabelFondoFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 720));

        pack();
    }// </editor-fold>                        

    private void jButtonSALIRActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        
       System.exit(0);
    }                                            

    private void jButton1IrAmenúclienteMouseClicked(java.awt.event.MouseEvent evt) {                                                    
        // TODO add your handling code here:
        Interfaz_MenuCliente iMR = new Interfaz_MenuCliente();
            iMR.setVisible(true);
            this.dispose();
    }                                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Facturación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Facturación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Facturación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Facturación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Facturación().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1IrAmenúcliente;
    private javax.swing.JButton jButtonSALIR;
    private javax.swing.JButton jButtonTotalAPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondoFacturacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextTotalAPagar;
    // End of variables declaration                   
}
